server:
  port: 8085

file-tracker:
  path: ${FILE_TRACKER_PATH}

executor:
  keep-alive-in-seconds: 3

  queue:
    max-capacity: 1000

  processors:
    cpu-threads-count: ${CPU_THREADS_COUNT}

spring:
  mvc:
    static-path-pattern: /swagger*

springdoc:
  api-docs:
    path: /api-docs
