server:
  port: 8085

file-tracker:
#  path:
  path: D:/chesh/andrey/polytech/технополис/проект/anticheat_sample_solutions

spring:
  mvc:
    static-path-pattern: /swagger*

springdoc:
  api-docs:
    path: /api-docs
